### ISSUE TITLE
templateで使用するcontextの表記方法変更の提案 

### ISSUE THREAD

**Issue by aibou** [codenize-tools/radiosonde#4]
`context.sns_topic` の表記だと、Hashie::Mashのメソッドを呼ぶことになり、Hashクラス等で定義されているメソッド名と衝突するとパラメータ名よりも優先されてしまう。
（例えば、`context.count` は、`Hash#count` が呼ばれる。）

そのため、READMEで記載されている `context.sns_topic` という表記から `context[:sns_topic]` という表記に変更することを提案したいのですがどうでしょうか？

**Comment by winebarrel** [comment]
なるほどー、了解です。
表記かえますね。

**Comment by winebarrel** [comment]
変えてみました

**Comment by aibou** [comment]
遅くなってすみません、ありがとうございます！

**Comment by winebarrel** [comment]
クローズありがとうございます🙇
